[package]
name = "local/roblox-graybox"
description = "Local-first server-authoritative Roblox graybox prototype"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

[server-dependencies]

[dev-dependencies]
